### ISSUE TITLE
Consider support for django-1.6

### ISSUE THREAD

**Issue by ralphbean** [product-definition-center/product-definition-center#277]
django-1.6 is the version in RHEL7.  As far as I can tell, PDC requires django-1.8 which makes it difficult to ship on top of RHEL7.  Any idea if making it run on django-1.6 would be easy or hard?

**Comment by lubomir** [comment]
Historically, PDC did actually use Django 1.6. However, making it run on it now would be a major undertaking: among other code changes we would have to redo all database migrations (because those came in 1.7) and use [south](https://pypi.python.org/pypi/South/1.0.2). I doubt there is a backwards compatible way to do that.

**Comment by ralphbean** [comment]
No worries.  We'll fix this with a forward-compat python-django18 package for EPEL7 (or something like that).  Thank you!
