### ISSUE TITLE
package in what image

### ISSUE THREAD

**Issue by matysek** [product-definition-center/product-definition-center#368]
Hello,
* is there a way to find out what images contain a specific package without the need to manually examine the content of images?
* does pdc even keep track of that?

For example:
* latest docker image for fc24 is Fedora-Cloud-Base-24_Beta-1.6.x86_64.raw.xz
* this tells me something about the image
  * itself: https://pdc.fedoraproject.org/rest_api/v1/images/?file_name=Fedora-Cloud-Base-24_Beta-1.6.x86_64.raw.xz
  * I found out it is based on compose Fedora-24-20160504.0
* then this endpoint tells me what all images were created from this compose:
  * https://pdc.fedoraproject.org/rest_api/v1/compose-images/Fedora-24-20160504.0/
* then I though that I might get somehow what packages are in this compose:
  * https://pdc.fedoraproject.org/rest_api/v1/compose-rpms/Fedora-24-20160504.0/

The endpoint `compose-rpms` still does not tell me if an rpm is bundled in the docker image or not. I suppose that docker image contains just a subset of rpms than that are in the compose.

Is there any better than `compose-rpms`?

Thanks

**Comment by lubomir** [comment]
PDC does not keep track of what is in images in a compose. The `compose-rpms` resource will show you what packages are in which variant and arch, but due to the way Fedora images are build they have packages from Everything variant, so that will not tell you much either.

The metadata that is imported into PDC does not have this information, so if we want to track it, it would need to change there as well.

If you only need this out of curiosity, you could go digging into [fedora-kickstarts](https://pagure.io/fedora-kickstarts) or find the Koji tasks that created the image (like [this one](http://koji.fedoraproject.org/koji/taskinfo?taskID=14166938)).

**Comment by matysek** [comment]
* Is there any plan to track that?
* How hard would it be to implement this?

* Do you think it makes sense to keep track of image types and list of components that are put into an image?
  * For example, image type would be 'Fedora-cloud-base' and then for this type you would have that it contains 'samba', 'git', 'libfoo', 'libbar', .... - not directly what version.
  * Makes this even sense or the list of packages that go into an image is changing with every fedora release?
  * This is just an idea that pops up in my head when PDC would not track directly content of images.

**Comment by lubomir** [comment]
@sochotnicky is the right person for plans.

**Comment by dmach** [comment]
As a side note... I know it's not applicable to almost any containers, but they ideally should have a header containing a list of all included artifacts. That list should be extracted from the container and uploaded to PDC.

PDC currently tracks only high-level information about images (name, checksums, etc.) because it's non-trivial to get to the artifact list. It often lives in build system or somewhere else rather than in the containers directly.

**Comment by sochotnicky** [comment]
@matysek You are probably looking for build-images endpoint: https://pdc.fedoraproject.org/rest_api/v1/build-images/

It can store contents of the images built through brew (including OSBS built ones). And you can "link" them to a release. These are separate from compose images (though I guess you could duplicate them for purpose of tracking the content).

**Comment by sochotnicky** [comment]
I'll assume the build-images API is fine. Getting the data into it is a separate thing
