### ISSUE TITLE
Review modularity changes

### ISSUE THREAD

**Issue by nphilipp** [product-definition-center/product-definition-center#407]
Hello!

As discussed, please take a look at the changes we are working on for modularity. We've queued them up here: https://github.com/fedora-modularity/product-definition-center/tree/modularity

Our branch is currently a little behind your `master` branch, because (as I mentioned) `git rebase --preserve-merges` doesn't really cope well with preserving feature-"bracket"-merge commits in a sensible way.

**Comment by simozhan** [comment]
@nphilipp Generally it looks good to me.
Just one question i'd like to ask:
What is variant_release and variant_version? Does it mean variant for which release version, for example variant "client" for ceph1.3, or there is some versions for variant, i.e client1.0.
And some minor things i want to point out.
1. Is it ok to squash the migration files as many as possible?
2. This is the first version, i guess more test cases and flake8 fix will be added.
3.[Tree Api](https://github.com/fedora-modularity/product-definition-center/blob/modularity/pdc/apps/tree/views.py#L174)
4.[%s](https://github.com/fedora-modularity/product-definition-center/blob/modularity/pdc/apps/tree/serializers.py#L24)

**Comment by bliuredhat** [comment]
@nphilipp; Generally it looks good for me.
But there are some errors in documents;
1. For `unreleasedvariants`  API, when RETRIEVE a instance, the result include `build_deps`,`runtime_deps `and `koji_tag`; such as:
{
    "variant_id": string,
    "variant_uid": string,
    "variant_name": string,
    "variant_type": string,
    "variant_version": string,
    "koji_tag": string,
    "build_deps": [],
    "runtime_deps": []
}
2. For `unreleasedvariants`  API, when CREATE a instance: the input parameter need to contain `build_deps`,`runtime_deps ` and `koji_tag`. Otherwise, it will raise error info.

BTW, I prefer to add UPDATE method for both two APIs, because `viewsets` is inherited from `PDCModelViewSet`, which inherited  `ChangeSetUpdateModelMixin` class.

**Comment by nphilipp** [comment]
> What is variant_release and variant_version? Does it mean variant for which release version, for example variant "client" for ceph1.3, or there is some versions for variant, i.e client1.0.

It's terminology which we've largely borrowed from RPMs I suppose, a version/release of the UnreleasedVariant (in our case, a module). We're discussing the specific semantics at the moment and it seems that we want to get away from the RPM-like meaning  of these **for modules**, i.e. where there is an order making one version "less" or "older" than another, going to something more like a "flavor" of a module, say a "LAMP" module with MySQL vs. one with MariaDB.

Of course, `UnreleasedVariant` needs to be generic enough to cater for other use cases as well, so I'm pretty open to not have two separate fields (for the use of modules), but one where whatever a module or other variants use gets encoded as a string.

> And some minor things i want to point out.
> 1. Is it ok to squash the migration files as many as possible?

Do you mean "too many commits, please squash into one"? If so, I'm not a huge friend of it—if we introduce bugs with our changes, I'd like to be able to bisect the history to find the culprit. This is almost impossible with one monolithic commit. I'd rather have merge-commits bracketing the changes, which looks like the best of both worlds to me: we still have the individual small changes, but also know how they are logically grouped, by individual feature, or by "this comes from the modularity folks". This would make out current stack of commits look like this:

```
*   4dd0832 Merge branch 'modularity' into foo
|\  
| *   de6d026 Merge pull request #5 from nphilipp/modularity-fixes/deps-serializing
| |\  
| | * b59869d (Un)Serialize dependencies as simple strings.
| |/  
| *   135d9ae Merge pull request #6 from lkocman/iteration_fix
| |\  
| | * 6b3e613 fix RelatedManager not iterable by iterating over .all()
| |/  
| *   c867e50 Merge pull request #4 from lkocman/modularity-features/module-deps
| |\  
| | * 90a2ca9 Add exports for UnreleasedVariant *_deps
| | * 74cfdcb add UnreleasedVariant *_deps to filters
| | * ef5661c Don't require runtime_deps/build_deps in the API.
| | * b239709 implement querying of variant runtime/build deps
| |/  
| *   bf613a9 Merge pull request #3 from nphilipp/modularity-features/variant-version-release-plus-comments
| |\  
| | * 87d79cb Add comment to variant_version/_release API docs.
| | * 772c4d4 Don't require variant_version/_release in the API.
| | * 67558d7 Add variant_version/_release to release.Variant.
| | * 8fd8af5 Add comment to variant_version/_release.
| |/  
| *   3be1604 Merge pull request #1 from nphilipp/modularity-features/unreleased-trees
| |\  
|/ /  
| * 09206cb add missing fields to test API calls
| * 5c16798 API end points are plural, not singular
| * 3a21667 sync up filters with changes in the models
| * c7180dd Add lookup_field etc. to Tree/UnreleasedVariant.
| * 2b3bfd7 fix URLs in API docs
| * 3e5c1af add migrations for Tree and UnreleasedVariant
| * 165cce7 rename TreeVariant* to UnreleasedVariant*
| * 4c3e16e require django-jsonfield
| * 6e56899 move JSON test data to own file
| * a2e3144 Add initial version of tree app into pdc
| * 1320712 Add release variant type 'module'
|/  
* 0a6b697 Change doc description for compose/compose-images/compose-rpms
```

> 2. This is the first version, i guess more test cases and flake8 fix will be added.

Most of the code as you see it was "sewn together in a great hurry" for the Flock conference in Krakow earlier this month. Do you have a document outlining what kind of tests you want for e.g. a new model/view/filter/... class? As far as flake8 goes I assume that you want the new code to pass when run through the program, right? 

> 3.Tree Api
> 4.%s

Oops. Good catch!

**Comment by nphilipp** [comment]
@bliuredhat:

> 1. For `unreleasedvariants` API, when RETRIEVE a instance, the result include **build_deps,runtime_deps** and **koji_tag**; such as:
>
>  {
>  "variant_id": string,
>  "variant_uid": string,
> "variant_name": string,
> "variant_type": string,
> "variant_version": string,
> "koji_tag": string,
> "build_deps": [],
> "runtime_deps": []
> }
> 2. For `unreleasedvariants` API, when CREATE a instance: the input parameter need to contain **build_deps,runtime_deps** and **koji_tag**. Otherwise, it will raise error info.

Hmm, the missing `koji_tag` must have been an omission, but `build_deps` and `runtime_deps` can be empty, so shouldn't be required in the API when submitting. Unfortunately I'm not overly familiar with Django and was going by reading existing code as an example, i.e. cargo-culting at times ;). 

> BTW, I prefer to add UPDATE method for both two APIs, because `viewsets` is inherited from `PDCModelViewSet`, which inherited `ChangeSetUpdateModelMixin` class. And I also consider that the UPDATE method is useful when we use the APIs.

Yeah, probably.

**Comment by simozhan** [comment]
@nphilipp Thanks for answering my question, i got it.
> 1. Is it ok to squash the migration files as many as possible?
For this one, i am guessing in the future there will be one commit to merge back to our repo, and i was hoping to squash the migration files(for example: 0007_add_release_variant_type_module.py and 0008_auto_20160719_1221.py or others). Your point is reasonable, so this is really a minor thing.
> 2. This is the first version, i guess more test cases and flake8 fix will be added.
I saw there are two test cases to create unreleasevariant and tree. There should be more test cases added in the future, for example, update/destroy/query ... test cases. And about the flake8 check for code convention, you can simply run "make flake8" and see there are some issues.

**Comment by ycheng-aa** [comment]
@nphilipp 
1. About the (unicode method)[https://github.com/fedora-modularity/product-definition-center/blob/modularity/pdc/apps/tree/models.py#L25], should the output at lease include the unique set, here is  ("variant_uid", "variant_version", "variant_release") ? Or different object may have the same string output.

2.In (here)[https://github.com/fedora-modularity/product-definition-center/blob/modularity/pdc/apps/tree/serializers.py#L30], I am not quite sure what will happen if we don't have the following 2 methods. Will it be the same?

3. In (create)[https://github.com/fedora-modularity/product-definition-center/blob/modularity/pdc/apps/tree/serializers.py#L96], it looks at least should check uniqueness in validate or in create and through proper exception. Or maybe the exception from DB will be thrown directly. E.g. create same UnreleasedVariant twice.

4. In (documentation)[https://github.com/fedora-modularity/product-definition-center/blob/modularity/pdc/apps/tree/views.py#L22], it says could use `put` method, but no `update` method documentation.  Same as some other viewsets. But the update method is still supported just no documentation, right? 

5. After you rebased master, permission control may take effect because `PDCModelViewSet` will inherit `PermissionMixin`. Hope this feature won't bring unexpected result.

**Comment by nphilipp** [comment]
Thank you for the quick response!

@simozhan:

1. Oh, I misread that completely, where you wrote "migration" I read "modularization" and I was like "no way I'm gonna squash all our work into one single commit" :wink:—I shouldn't have replied at the end of my work day :smiley:. Of course, squashing the migrations isn't a problem.

2. I'm totally with you, we should cover all angles of newly introduced things as far as unit testing goes. I have the `vim-flake8` plugin installed, so should be covered re: flake8, but need to check why its output sometimes gets overwritten...

@ycheng-aa:

1. Good point. I guess that our team needs to finalize the discussion on versioning, then we can fix that part for good.

2. To be honest, I don't know. See my comment about my understanding (or lack thereof) of Django above :wink:. Looks pretty NOOP to me, too, but I have to ask the person who wrote it.

3. Yes, that would pass through the exception from the DB layer. We can wrap it into something more fitting for serializers if you want, if so, do you have an example in another part of PDC how it should rather be done?

4. Agreed, the documentation and the code should match, one way or the other.

5. I understand that we want to restrict access to at least the methods that change things in the database, and as we use `pdc-client` that should work in theory :smiley:. Does inheriting from `PermissionMixin` entail any other restrictions?

**Comment by nphilipp** [comment]
@lkocman, @ralphbean, anything I missed in the discussion above?

**Comment by ycheng-aa** [comment]
@nphilipp 
About `3`, I think usually `ModelSerializer` will take care of uniqueness violation automatically. Because here `create` is overrided, I think maybe use `try/exception/raise` in`validate` method could solve this. Maybe there is other better ways. There is an [old pr](https://github.com/product-definition-center/product-definition-center/pull/409), but I am also not sure it is good way.

About `4`, Thanks. I think the APIs maybe are still supporting `update` method even it is not defined explicitly. Maybe it use super's `update` method directly. If so, I think it's not what you expected. The newly added viewsets inherit `viewsets.PDCModelViewSet`. It supports `update` method.

About `5`, PDC team implemented resource permission control recently, it could restrict or assign CRUD permission for an API to a specific group. Please refer to API `auth/resource-permissions` and `auth/group-resource-permissions`. If after resource permissions are generated, but a group haven't been granted the priviledge, this group will not have corresponding permission to access the API(resource). But all legal users  have `read` permission for all APIs in default.

**Comment by ralphbean** [comment]
I somehow forgot about the existence of this discussion.  It is relevant to #431.

**Comment by ralphbean** [comment]
This can probably be closed.

**Comment by simozhan** [comment]
Yeah. Closed
