### ISSUE TITLE
Filtering unreleasedvariants for component_branch doesn't seem to work correctly

### ISSUE THREAD

**Issue by fivaldi** [product-definition-center/product-definition-center#458]
Background: https://pagure.io/releng/pull-request/6970

It seems that filtering `unreleasedvariants` for `component_branch` doesn't return the desired results.

E.g.: If I query https://pdc.fedoraproject.org/rest_api/v1/unreleasedvariants/?component_branch=master&component_name=wayland I receive 4 modules currently which should contain the desired component with the corresponding branch.

If I then query `rpms` directly ( https://pdc.fedoraproject.org/rest_api/v1/rpms/?name=wayland&srpm_commit_branch=master ), I don't get any records. I also tried querying `srpm_name` param instead of `name` with no luck..

**Comment by hluk** [comment]
The filter fields `component_branch` and `component_name` are independent, i.e. they can match different `rpms` entries.

So the expected behavior is to match single rpm with both `component_branch` and `component_name`? And I guess this would be the same for filters `runtime_dep_name`/`runtime_dep_stream` and `build_dep_name`/`build_dep_stream`?

There are other APIs to which this would apply.

**Comment by sochotnicky** [comment]
Behaviour should always be that repeat of the same filter argument means "OR" and providing multiple (different) filtering arguments should be interpreted as "AND". That's the logical way to interpret the arguments IMO
